export const GET_USERS_COUNT = 'GET_USERS_COUNT';
export const GET_ORDERS_COUNT = 'GET_ORDERS_COUNT';

export const GET_USERS_LIST = 'GET_USERS_LIST';
export const GET_ORDERS_LIST = 'GET_ORDERS_LIST';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_ORDERS = 'GET_USER_ORDERS';
